# Dataset configuration
dataset_path: "../datasets"
dataset: "cifar10"
supervised_ratio: 0.08

# Training configuration
model: wideresnet28_2
batch_size: 128
epoch: 200
optimizer: supervised   # look at supervisor.py
resume: False

# Miscalenous
checkpoint_path: "../model_save/cifar10/supervised"
tensorboard_path: "../tensorboard/cifar10/supervised"
tensorboard_sufix: ""