# Dataset configuration
dataset_path: "../datasets"
dataset: "cifar10"
supervised_ratio: 0.1

# Training configuration
model: wideresnet28_2
batch_size: 100
epoch: 300
learning_rate: 0.1
optimizer: dct   # look at supervisor.py
resume: False

# Miscalenous
checkpoint_path: "../model_save/cifar10/co-training"
tensorboard_path: "../tensorboard/cifar10/co-training"
tensorboard_sufix: ""