
# Dataset configuration
dataset_root: "../../datasets"
dataset: "SpeechCommand"

# Training configuration
model: wideresnet28_2
supervised_ratio: 0.1
learning_rate: 0.003
batch_size: 64
nb_epoch: 200

lambda_ccost_max: 1
warmup_length: 50
alpha: 0.999

resume: "false"
seed: 1234
num_classes: 10

# Miscalenous
checkpoint_root: "../../model_save"
checkpoint_path: "deep-co-training"
tensorboard_root: "../../tensorboard"
tensorboard_path: "deep-co-training"
tensorboard_sufix: ""